version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_DB: nth-ls-db
      POSTGRES_USER: vortex332
      POSTGRES_PASSWORD: hashim123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
